// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import { faker } from '@faker-js/faker';

// BEGIN EXTRA CODE
async function createMxObject(entityName) {
	return new Promise(function(resolve, reject) {
		mx.data.create({
			entity: entityName,
			callback: function(mxObject) {
				resolve(mxObject);
			},
			error: function(e) {
				reject("Could not create object:" + e.message);
			}
		});
	});
}
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject>}
 */
export async function JSA_Vehicle_Create() {
	// BEGIN USER CODE
	const name = faker.vehicle.vehicle();
	const model = faker.vehicle.model();
	const manufacturer = faker.vehicle.manufacturer();
	const color = faker.vehicle.color();
	const fuel = faker.vehicle.fuel();
	const year = faker.date.past().getFullYear();
	const vrm = faker.vehicle.vrm();

	const newVehicle = await createMxObject("App.Vehicle");
	newVehicle.set("Name", name);
	newVehicle.set("Model", model);
	newVehicle.set("Manufacturer", manufacturer);
	newVehicle.set("Color", color);
	newVehicle.set("Fuel", fuel);
	newVehicle.set("Year", year);
	newVehicle.set("Vrm", vrm);

	return newVehicle;
	// END USER CODE
}
